name: Create Timestamp File and Archive

on: workflow_dispatch

jobs:
  create-and-archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a file with UNIX timestamp
      run: echo $(date +%s) > timestamp.txt

    - name: Archive the file as an artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: timestamp-artifact
        path: timestamp.txt
