name: Create Timestamp File and Archive

on: workflow_dispatch

jobs:
  create-and-archive:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a file with UNIX timestamp
      run: echo $(date +%s) > timestamp.txt

    - name: Archive the file as an artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: timestamp-artifact
        path: timestamp.txt

  upload-to-s3:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: create-and-archive

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Set up AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: timestamp-artifact

    # - name: Upload to S3
    #   run: aws s3 cp previous-artifact/ s3://your-bucket-name/ --recursive